### PR TITLE
1.part 2

### PR DESCRIPTION
**Pull request by Skertch**
Seeded petsitters
removed user_ID references from petsitters model
created petsitters controller
created new action and html to display petsitters

### CODE REVIEW

**Comment by Mai-wandK** [comment]
Looks great.

**Review by loadsmile — APPROVED** [review]
Looks file! You can merge, thank you!

**Review by Mai-wandK — COMMENTED** [review]
Looks great.

**Review by neusgomis — COMMENTED** [review]
looks good

**Pull request merged**
